development:
   oauth:
      application:
         name: ClearInsight
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'http://www.cz-tek.com'
         owner: admin@ci.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: clearinsight
   oss:
       aliyun_access_id: VDXgx2g1F7gZe8SY
       aliyun_access_key: cVJoHKSh377Al7il90VuQD7Fo1GiPG
       aliyun_bucket: clearinsight-test
       aliyun_upload_host: http://clearinsight-test.oss-cn-hangzhou.aliyuncs.com
       aliyun_internal: false
       aliyun_area: cn-hangzhou
   thumb:
       follow_snap: 'uploads/attach/logo.png'
   snap:
       chart_data: 'uploadfiles/data/data.json'
   kafka_server:
       host_port: 'localhost:9092'


demo:
   oauth:
      application:
         name: ClearInsight
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'https://www.cz-tek.com'
         owner: admin@ci.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: clearinsight
   oss:
       aliyun_access_id: VDXgx2g1F7gZe8SY
       aliyun_access_key: cVJoHKSh377Al7il90VuQD7Fo1GiPG
       aliyun_bucket: clearinsight-test
       aliyun_upload_host: http://clearinsight-test.oss-cn-hangzhou-internal.aliyuncs.com
       aliyun_internal: true
       aliyun_area: cn-hangzhou
   thumb:
       follow_snap: 'uploads/attach/logo.png'
   snap:
       chart_data: 'uploadfiles/data/data.json'
   kafka_server:
       host_port: 'localhost:9092'

# local env for test, like store attach on local not oss
local:
   oauth:
      application:
         name: ClearInsight
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'https://www.cz-tek.com'
         owner: admin@ci.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: clearinsight
   oss:
       aliyun_access_id: VDXgx2g1F7gZe8SY
       aliyun_access_key: cVJoHKSh377Al7il90VuQD7Fo1GiPG
       aliyun_bucket: clearinsight-test
       aliyun_upload_host: http://clearinsight-test.oss-cn-hangzhou.aliyuncs.com
       aliyun_internal: false
       aliyun_area: cn-hangzhou
   thumb:
       follow_snap: 'uploads/attach/logo.png'
   snap:
       chart_data: 'uploadfiles/data/data.json'
   kafka_server:
       host_port: 'localhost:9092'


production:
   oauth:
      application:
         name: ClearInsight
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'https://www.cz-tek.com'
         owner: admin@ci.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: clearinsight
   oss:
       aliyun_access_id: VDXgx2g1F7gZe8SY
       aliyun_access_key: cVJoHKSh377Al7il90VuQD7Fo1GiPG
       aliyun_bucket: clearinsight-test
       aliyun_upload_host: http://clearinsight-test.oss-cn-hangzhou-internal.aliyuncs.com
       aliyun_internal: true
       aliyun_area: cn-hangzhou
   thumb:
       follow_snap: 'uploads/attach/logo.png'
   snap:
       chart_data: 'uploadfiles/data/data.json'
   kafka_server:
       host_port: 'localhost:9092'
