#coding:utf-8
# format settings
format:
 :csv_splitor: ';'
 :update_marker: 'DOUPDATE'
 :file_max_size: 20971520
 
path:
 :updata_file_path: 'uploadfiles/data'
 :download_file_path: 'uploadfiles/download'
 :template_file_path: 'uploadfiles/template'
 :kpi_entry_file_path: 'uploadfiles/kpi_entry'
 :avatar_file_path: 'uploadfiles/avatar'
 :email_file_path: 'uploadfiles/emails'
 :attach_tmp_path: 'uploadfiles/attach/tmp'
 :attach_path: 'uploadfiles/attach/uped'
 :tmp_file_path: 'uploadfiels/tmp'
