#coding:utf-8
# format settings
format:
 :csv_splitor: ';'
 :update_marker: 'DOUPDATE'
 
path:
 :updata_file_path: 'uploadfiles/data'
 :download_file_path: 'uploadfiles/download'
 :template_file_path: 'uploadfiles/template'
