paths:
   jquery: "libs/jquery-1.8.2.min"
   mustache: "libs/mustache"
   chart: "libs/Chart.min"
   lowchart: "simple_chart/chart_generate"
   base: "func-module/wayne_base"
   jquery.icheck: "libs/jquery.icheck.min"
   icheck: "func-module/icheck"
   jquery.sortable: "libs/jquery.sortable.min"
   jquery.tipsy: "libs/jquery.tipsy"
   jquery.baresize: "libs/jquery.ba-resize.min"
   jquery.chosen: "libs/chosen.jquery.min"
   chosen: "func-module/chosen"
   bootstrap.datepicker: "libs/bootstrap-datepicker"
   datepicker: "func-module/datepicker"
   jquery.fileupload: "libs/jquery.fileupload"
   jquery.ui.widget: "libs/jquery.ui.widget"
   bootstrap.datetimepicker: "libs/bootstrap-datetimepicker.min"
   jquery.sparkline: "libs/jquery.sparkline.min"
shim:
   chart:
      exports: "Chart"
   jquery.icheck:
      deps: ["jquery"]
      exports: "jQuery.fn.iCheck"
   jquery.sortable:
      deps: ["jquery"]
      exports: "jQuery.fn.sortable"
   jquery.tipsy:
      deps: ["jquery"]
      exports: "jQuery.fn.tipsy"
   jquery.baresize:
      deps: ["jquery"]
      exports: "jQuery.fn.resize"
   jquery.chosen:
      deps: ["jquery"]
      exports: "jQuery.fn.chosen"
   bootstrap.datepicker:
      deps: ["jquery"]
      exports: "jQuery.fn.datepicker"
   bootstrap.datetimepicker:
      deps: ["jquery"]
      exports: "jQuery.fn.datetimepicker"
   jquery.fileupload:
      deps: ["jquery",jquery.ui.widget]
      exports: "jQuery.fn.fileupload"
   jquery.sparkline:
      deps: ["jquery"]
      exports: "jQuery.fn.sparkline"
