# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
#:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 20
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
#  - [often, 7]
  - [default, 5]
#  - [seldom, 3]
  - [kpicaljob,7]
#  - [email,7]
