#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require_relative 'hbase_types'

module Epm
  module Hbase
    module Thrift
    end
  end
end
